{% set name = "hypothesis-rdkit" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypothesis-rdkit-{{ version }}.tar.gz
  sha256: 82e873915f32519cb0170a7c6cc89543380ba898262e82829f49b6113480da17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - rdkit
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - hypothesis
    - numpy
    - tqdm
    - platformdirs
    - rdkit

test:
  imports:
    - hypothesis_rdkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/shirte/hypothesis-rdkit
  summary: Hypothesis strategies for RDKit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shirte
