{% set name = "hypothesis-rdkit" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypothesis-rdkit-{{ version }}.tar.gz
  sha256: 166867e2c34be8331f40f22d2a356f8fb0cf6e4efd0833ec6668f63e0087943d

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - rdkit
    - pip
  run:
    - python
    - hypothesis
    - numpy
    - tqdm
    - importlib-resources >=5  # [py<39]
    - importlib-metadata >=4.6  # [py<310]
    - platformdirs
    - rdkit

test:
  imports:
    - hypothesis_rdkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/shirte/hypothesis-rdkit
  summary: Hypothesis strategies for RDKit
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shirte
